### ISSUE TITLE
If a network error prevents the STS call, the web page hangs

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-aws-cli#100]
If there's a network error when calling the STS endpoint the web page hangs at `Retrieving EISProdAdmin role, please hold.` and this error text is shown in verbose mode.

We should handle this second exception triggered on the first exception and gracefully show an error message in the web tab 

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sts.amazonaws.com', port=443): Max retries exceeded with url: /?Action=AssumeRoleWithWebIdentity&RoleArn=arn%3Aaws%3Aiam%3A%3A371522382791%3Arole%2FEISProdAdmin&RoleSessionName=federated-aws-cli-gene&WebIdentityToken=eyJ0eXAiOiJKV1QiREDACTEDqOUHv2mfA&Version=2011-06-15 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2f70494a20>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/gene/.virtualenvs/federated_aws_cli/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/.virtualenvs/federated_aws_cli/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/.virtualenvs/federated_aws_cli/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/.virtualenvs/federated_aws_cli/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/gene/.virtualenvs/federated_aws_cli/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/.virtualenvs/federated_aws_cli/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/code/github.com/gene1wood/federated-aws-cli/federated_aws_cli/listener.py", line 129, in handle_oidc_redirect_callback
    redirect = login.get_id_token(**request.json)
  File "/home/gene/code/github.com/gene1wood/federated-aws-cli/federated_aws_cli/login.py", line 243, in get_id_token
    role_arn=self.role_arn
  File "/home/gene/code/github.com/gene1wood/federated-aws-cli/federated_aws_cli/sts_conn.py", line 37, in get_credentials
    resp = requests.get(url=sts_url, params=parameters)
  File "/home/gene/.virtualenvs/federated_aws_cli/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/gene/.virtualenvs/federated_aws_cli/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/gene/.virtualenvs/federated_aws_cli/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/gene/.virtualenvs/federated_aws_cli/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/gene/.virtualenvs/federated_aws_cli/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sts.amazonaws.com', port=443): Max retries exceeded with url: /?Action=AssumeRoleWithWebIdentity&RoleArn=arn%3Aaws%3Aiam%3A%3A371522382791%3Arole%2FEISProdAdmin&RoleSessionName=federated-aws-cli-gene&WebIdentityToken=eyJ0eXAREDACTEDHv2mfA&Version=2011-06-15 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2f70494a20>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
```

**Comment by gene1wood** [comment]
We should do some kind of a retry or detecting that there was a problem and gracefully exit. Here's the error I got today, this happened after selecting a role from the web role picker

```
$ python3 -m federated_aws_cli.cli -o shared -w
ERROR:flask.app:Exception on /redirect_callback [POST]
Traceback (most recent call last):
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fde3819eb38>: Failed to establish a new connection: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sts.amazonaws.com', port=443): Max retries exceeded with url: /?Action=AssumeRoleWithWebIdentity&RoleArn=arn%3Aaws%3Aiam%3A%3A371522382791%3Arole%2FEISProdAdmin&RoleSessionName=federated-aws-cli-gene&WebIdentityToken=eyJ0eREDACTEDiTBc4M4ez3Q&Version=2011-06-15 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fde3819eb38>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gene/code/github.com/gene1wood/federated-aws-cli/federated_aws_cli/listener.py", line 142, in handle_oidc_redirect_callback
    login.get_id_token(**request.json)
  File "/home/gene/code/github.com/gene1wood/federated-aws-cli/federated_aws_cli/login.py", line 256, in get_id_token
    role_arn=self.role_arn
  File "/home/gene/code/github.com/gene1wood/federated-aws-cli/federated_aws_cli/sts_conn.py", line 37, in get_credentials
    resp = requests.get(url=sts_url, params=parameters)
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/gene/.virtualenvs/federated-aws-cli/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sts.amazonaws.com', port=443): Max retries exceeded with url: /?Action=AssumeRoleWithWebIdentity&RoleArn=arn%3Aaws%3Aiam%3A%3A371522382791%3Arole%2FEISProdAdmin&RoleSessionName=federated-aws-cli-gene&WebIdentityToken=eyJ0eXAREDACTEDP4pZHiTBc4M4ez3Q&Version=2011-06-15 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fde3819eb38>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
```
