### ISSUE TITLE
Fix error when `config` file missing

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-aws-cli#129]
It looks like if you run maws without a `config` file it gives this error.
```
Traceback (most recent call last):
  File "/home/gene/.local/bin/maws", line 11, in <module>
    sys.exit(main())
  File "/home/gene/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/gene/.local/lib/python3.6/site-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/gene/.local/lib/python3.6/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/home/gene/.local/lib/python3.6/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/gene/.local/lib/python3.6/site-packages/click/core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/gene/.local/lib/python3.6/site-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/gene/.local/lib/python3.6/site-packages/mozilla_aws_cli/cli.py", line 82, in validate_config_file
    config['DEFAULT'].update(mozilla_aws_cli_config.config)
UnboundLocalError: local variable 'config' referenced before assignment
```

**Comment by gene1wood** [comment]
Released to pypi in v0.1.1
